### ISSUE TITLE
Logging guidance and PII data handling

### ISSUE THREAD

**Issue by ashayraut** [oauth-wg/oauth-transaction-tokens#124]
Currently logging guidance says "Txn-Tokens SHOULD NOT be logged if they contain Personally Identifiable Information (PII)". I have few questions on this one
1. Risks with logging is that token is still valid for few minutes and if logs are rotated to any other central archival storage with access to broader set of people or someone has access to the server with logs, then they can reuse the token. So why not just say MUST not log token?
2. Also how would a service know if incoming token has PII or not. They will have to validate the token, extract claims and then somehow know infer that a claim is PII or not. 
3. On similar lines, for PII , can we mention that TTS SHOULD evaluate encrypting  or tokenizing PII claims rather than adding them in plaintext. Adding in plaintext is a risk because TTS isn't aware where the token flows.

**Comment by obfuscoder** [comment]
Txn-Tokens already contain the subject identifier which is enough to be considered PII in some environments. Our own policy states that PII data can be logged, but the logs must be deleted after a few days (max 7) days.

We forbid logging of Txn-Tokens in our integrations for security reasons, not just because they could contain PII.

**Comment by ashayraut** [comment]
Our implementation in my company, we do follow the same guidance i.e do not log tokens at all, nothing to do with PII. Tokens are pretty much considered as credentials as validating parties leverage the claims for authorizing the request.
